apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: no5i68m3o-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: no5i68m3o-nodejs 
  name: no5i68m3o-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: no5i68m3o-nodejs 
